### ISSUE TITLE
single object tracking

### ISSUE THREAD

**Issue by woaixueyingying** [deepmind/perception_test#1]
I've observed that the static baseline only includes evaluation code without any training code. Additionally, in the competition, the SiamFC tracker from Unitrack is used as a baseline, but I couldn't find any training examples. Could you please provide training and evaluation examples based on Unitrack? This would save us participants some time.Looking forward to your reply.Thank you!

**Comment by viorik** [comment]
Indeed, we only included evaluation code. SiamFC was evaluated zero-shot on our benchmark, so no training is required.
For Unitrack implementation, this is their official repository https://github.com/Zhongdao/UniTrack/tree/main, there is a demo as well https://github.com/Zhongdao/UniTrack/blob/main/demo/sot_demo.py. If you try to run it and you are not sure about some parameter values, please post here and we will clarify.
