### ISSUE TITLE
the evaluation result for the test for the Grounded videoQA

### ISSUE THREAD

**Issue by runzeer** [deepmind/perception_test#2]
Dear;
    Thanks for your interesting tasks. But I have some issues for the Grounded videoQA task. I noticed that the results for the grounded videoQA are the subset of the SOT task. But in the SOT challenge website, is said
![image](https://github.com/deepmind/perception_test/assets/14292495/b28b5f0c-3be4-4ff7-9895-698a61e592dc)
But in the Grounded VideoQA, it did not say the result should be 1fps. And I also noticed that in the train or validation data, there exist some tracks, whose frame_ids interval are less than 30, e.g [300,330,337,343, 360..., 420, 450]. So I wonder whether I should submit the track for the frame-wise or the second-wise for every 30 frames.  Looking forward to your reply.

**Comment by ptchallenge-workshop** [comment]
Thanks for raising this issue. Please submit all predictions for the single object tracking and grounded videoQA tasks during test phase and we will filter the predictions based on the annotated frame ids. This may make submission files too large to upload via the challenge page, the submission page can struggle with files >200MB so any files larger than this should probably be submitted via the command line interface. There are instructions on the submission page for this upload method. We will update the corresponding challenge pages to clarify this.
