### ISSUE TITLE
About single object track, test phrase

### ISSUE THREAD

**Issue by songtianhui** [deepmind/perception_test#3]
Hi, I am confused about the test phrase in single object tracking challenge.
As demonstrated in the notebook, the tracking results per frame will be filtered by the `frame_ids` for evaluation and submit.
But in test annotations, the length of `frames_ids` is exactly `1`. What is the correct submission format for test phrase? Report all frames results? What format of `frame_ids` should be in result file?

**Comment by songtianhui** [comment]
Thanks for reply!
Another thing I want to check is that the `frame_ids` should also be like `[0, 1, 2, ..., num_frames]` since all frame results are contained?

**Comment by ptchallenge-workshop** [comment]
We expect the format for frame IDs to be like [start_frame_id, ..., num_frames]

start_frame_id can be found in each phase by:

-  In validation phase 'initial_tracking_box' field is a one-hot vector that indicates which frame ID in 'frame_ids' is the start_frame_id
- In test phase we only provide start_frame_id in the 'frame_ids' field.

Please let me know if that isn't clear

**Comment by songtianhui** [comment]
Get it! Thanks for clarification!
